added formula editor showcase
getfundwave/fw-components pull request #22
Opened 2024-12-24 17:17 UTC by Govind-Jangra

#### Description

1. Added showcase for formula editor
2. Made some configuration changes in formula-editor package for build purpose (added tsconfiq.json)

2025-01-09 05:28 UTC, Govind-Jangra commented on .github/workflows/deploy.yml
> +        export NODE_OPTIONS=--openssl-legacy-provider
Above node version >16, some cryptographic algorithms became legacy for better security. But still some packages uses the old version of algorithms. So I add these to support older algorithms in node version >16.
[https://github.com/webpack/webpack/issues/14532#](url)

2025-01-09 07:01 UTC, paras-fundwave requested changes
requires minor changes

looks good otherwise

2025-01-09 07:01 UTC, paras-fundwave commented on packages/formula-editor/src/formula-editor.ts
> +    else if (event.code == "ArrowDown" || event.code == "ArrowUp") {
prefer strict equality

2025-01-09 07:01 UTC, paras-fundwave commented on packages/formula-editor/src/suggestion-menu.ts
> +      color: yellow;
use css variables with fallbacks as being done already

2025-01-09 07:01 UTC, paras-fundwave commented on showcase/fw-dnd/package.json
> +    "build": "webpack --config webpack.dev.js --stats verbose",
can rename the dev file to be just webpack.js as this doesn't require prod and dev builds

2025-01-09 07:01 UTC, paras-fundwave commented on packages/formula-editor/src/formula-editor.ts
> +    let newIndex = currentIndex;
avoid let can directly do assignments within the if blocks

2025-01-09 07:01 UTC, paras-fundwave commented on packages/formula-editor/src/formula-editor.ts
>    handleTab(event: KeyboardEvent) {
can rename as it doesn't just handle `Tab` event maybe handleKeyboardEvents

2025-01-09 07:01 UTC, paras-fundwave commented on packages/formula-editor/src/parser.ts
> +    calculationResult.result=parseFloat(calcStack.top().toString());
why the conversion from string back to float?

also, need to format files

2025-01-09 07:20 UTC, Govind-Jangra commented on packages/formula-editor/src/parser.ts
> +    calculationResult.result=parseFloat(calcStack.top().toString());
Big js does not support conversion to number so I first convert it to string then number.

2025-01-09 07:23 UTC, Govind-Jangra commented on packages/formula-editor/src/formula-editor.ts
> +    let newIndex = currentIndex;
Yeah sure I will take care. Here the code will become repeated in this scenario so I used let.

2025-01-09 10:03 UTC, paras-fundwave commented on packages/formula-editor/src/parser.ts
> +    calculationResult.result=parseFloat(calcStack.top().toString());
so this wasn't working earlier?

2025-01-09 10:10 UTC, Govind-Jangra commented on packages/formula-editor/src/suggestion-menu.ts
> +      color: yellow;
Done https://github.com/getfundwave/fw-components/pull/22/commits/8a85f6775bc4b5263479bbe041e95c863f711f70

2025-01-09 10:10 UTC, Govind-Jangra commented on packages/formula-editor/src/formula-editor.ts
>    handleTab(event: KeyboardEvent) {
Done https://github.com/getfundwave/fw-components/pull/22/commits/a9b3a6ab73a19c7eeb276d2d85c03e688b42330b

2025-01-09 10:11 UTC, Govind-Jangra commented on packages/formula-editor/src/formula-editor.ts
> +    let newIndex = currentIndex;
Done https://github.com/getfundwave/fw-components/pull/22/commits/abc20dd93f725f5861447274fa61f6ba3bd4edfd

2025-01-09 10:11 UTC, Govind-Jangra commented on showcase/fw-dnd/package.json
> +    "build": "webpack --config webpack.dev.js --stats verbose",
Done https://github.com/getfundwave/fw-components/pull/22/commits/a9b3a6ab73a19c7eeb276d2d85c03e688b42330b

2025-01-09 10:12 UTC, Govind-Jangra commented on packages/formula-editor/src/formula-editor.ts
> +    else if (event.code == "ArrowDown" || event.code == "ArrowUp") {
Done https://github.com/getfundwave/fw-components/pull/22/commits/a9b3a6ab73a19c7eeb276d2d85c03e688b42330b

2025-01-09 10:24 UTC, Govind-Jangra commented on packages/formula-editor/src/parser.ts
> +    calculationResult.result=parseFloat(calcStack.top().toString());
No this was not working in parse.js file. I tried with the new file to test the toNumber functionality and it works on the test file.

2025-01-14 12:43 UTC, paras-fundwave approved these changes

2025-01-14 12:45 UTC, merged